# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='status',
            field=models.TextField(default=b'UNKNOWN'),
        ),
    ]
